version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "rhysmdnz"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "rhysmdnz"

  - package-ecosystem: "cargo"
    directory: "/wasm"
    schedule:
      interval: "monthly"
    assignees:
      - "rhysmdnz"
