name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install minimal stable rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - uses: Swatinem/rust-cache@v1
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Install node dependencies
      run: |
        wasm-pack build wasm
        yarn install
    - name: Build
      run: yarn run build
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.MY_TOKEN }}
        publish_dir: ./dist
        external_repository: printfn/unicode-unicorn-website
        force_orphan: true
        cname: unicode.website
