name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install minimal stable rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - uses: Swatinem/rust-cache@v1
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Install node dependencies
      run: |
        npm ci
    - name: Build
      run: npm run build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: |
          dist

  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: "build"
    environment: production
    concurrency: production
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: dist
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.MY_TOKEN }}
        publish_dir: ./dist
        external_repository: printfn/unicode-unicorn-website
        force_orphan: true
        cname: unicode.website
