name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: cargo-registry-${{ hashFiles('wasm/Cargo.lock') }}
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: cargo-index-${{ hashFiles('wasm/Cargo.lock') }}
    - name: Cache rust build
      uses: actions/cache@v1.0.1
      with:
        path: wasm/target
        key: build-${{ hashFiles('wasm/Cargo.lock') }}
    - name: Install node dependencies
      run: yarn install
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Build
      run: yarn run build
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.MY_TOKEN }}
        publish_dir: ./build
        external_repository: printfn/unicode-unicorn-website
        force_orphan: true
        cname: unicode.website
